name: Build Release

on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    name: Create Release
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create a Release
        run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
      
  upload:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        php: [ 7.4 ]

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          working_dir:  ${{ github.event.repository.name }}

      - name: Archive
        run: rm -rf "${{ github.event.repository.name }}/.git" "${{ github.event.repository.name }}/.github" && zip -r ${{ github.event.repository.name }}-php-${{ matrix.php }}.zip ./${{ github.event.repository.name }}

      - name: Upload
        run: gh release upload ${{ github.ref_name }} ${{ github.event.repository.name }}-php-${{ matrix.php }}.zip
        env:
          GH_TOKEN: ${{ github.token }}
